version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=bayanai.settings
      - DATABASE_URL=postgres://abdoulam:iohnrfiohcn74729299913@db:5432/e_stock
    depends_on:
      - db
  db:
    image: postgres:13
    volumes :
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=e_stock
      - POSTGRES_USER=e-stock
      - POSTGRES_PASSWORD=iohnrfiohcn74729299913
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:       
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:



